# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'glatting.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(863, 483)
        self.glattingOrigGrey = QtWidgets.QPushButton(Form)
        self.glattingOrigGrey.setGeometry(QtCore.QRect(370, 390, 89, 25))
        self.glattingOrigGrey.setObjectName("glattingOrigGrey")
        self.garden = QtWidgets.QPushButton(Form)
        self.garden.setGeometry(QtCore.QRect(750, 200, 89, 25))
        self.garden.setObjectName("garden")
        self.ocean = QtWidgets.QPushButton(Form)
        self.ocean.setGeometry(QtCore.QRect(750, 280, 89, 25))
        self.ocean.setObjectName("ocean")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(750, 320, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.glattetColour = QtWidgets.QPushButton(Form)
        self.glattetColour.setGeometry(QtCore.QRect(470, 390, 89, 25))
        self.glattetColour.setObjectName("glattetColour")
        self.konstant = QtWidgets.QDoubleSpinBox(Form)
        self.konstant.setGeometry(QtCore.QRect(670, 390, 69, 26))
        self.konstant.setDecimals(1)
        self.konstant.setMinimum(1.0)
        self.konstant.setMaximum(4.0)
        self.konstant.setObjectName("konstant")
        self.glattingOriginal = QtWidgets.QPushButton(Form)
        self.glattingOriginal.setGeometry(QtCore.QRect(270, 390, 89, 25))
        self.glattingOriginal.setObjectName("glattingOriginal")
        self.glattingOverskrift = QtWidgets.QLabel(Form)
        self.glattingOverskrift.setGeometry(QtCore.QRect(40, 30, 761, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.glattingOverskrift.setFont(font)
        self.glattingOverskrift.setObjectName("glattingOverskrift")
        self.mountains = QtWidgets.QPushButton(Form)
        self.mountains.setGeometry(QtCore.QRect(750, 240, 89, 25))
        self.mountains.setObjectName("mountains")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(40, 110, 191, 221))
        self.label_12.setObjectName("label_12")
        self.balls = QtWidgets.QPushButton(Form)
        self.balls.setGeometry(QtCore.QRect(750, 120, 89, 25))
        self.balls.setObjectName("balls")
        self.adjuster = QtWidgets.QPushButton(Form)
        self.adjuster.setGeometry(QtCore.QRect(750, 80, 89, 25))
        self.adjuster.setObjectName("adjuster")
        self.glattingKode = QtWidgets.QPushButton(Form)
        self.glattingKode.setGeometry(QtCore.QRect(20, 390, 131, 25))
        self.glattingKode.setObjectName("glattingKode")
        self.fog = QtWidgets.QPushButton(Form)
        self.fog.setGeometry(QtCore.QRect(750, 160, 89, 25))
        self.fog.setObjectName("fog")
        self.trees = QtWidgets.QPushButton(Form)
        self.trees.setGeometry(QtCore.QRect(750, 360, 89, 25))
        self.trees.setObjectName("trees")
        self.glattetGrey = QtWidgets.QPushButton(Form)
        self.glattetGrey.setGeometry(QtCore.QRect(570, 390, 89, 25))
        self.glattetGrey.setObjectName("glattetGrey")
        self.glattingBilde = QtWidgets.QLabel(Form)
        self.glattingBilde.setGeometry(QtCore.QRect(270, 76, 471, 301))
        self.glattingBilde.setText("")
        self.glattingBilde.setPixmap(QtGui.QPixmap("../../hdr-bilder/Adjuster/Adjuster_00032.png"))
        self.glattingBilde.setScaledContents(True)
        self.glattingBilde.setObjectName("glattingBilde")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.glattingOrigGrey.setText(_translate("Form", "Gråtone"))
        self.garden.setText(_translate("Form", "Garden"))
        self.ocean.setText(_translate("Form", "Ocean"))
        self.pushButton.setText(_translate("Form", "Stillife"))
        self.glattetColour.setText(_translate("Form", "Glatt"))
        self.glattingOriginal.setText(_translate("Form", "Original"))
        self.glattingOverskrift.setText(_translate("Form", "Glatting av bilde"))
        self.mountains.setText(_translate("Form", "Mountains"))
        self.label_12.setText(_translate("Form", "**Tekst om funksjonalitet**"))
        self.balls.setText(_translate("Form", "Balls"))
        self.adjuster.setText(_translate("Form", "Adjuster"))
        self.glattingKode.setText(_translate("Form", "Vis kode"))
        self.fog.setText(_translate("Form", "Fog"))
        self.trees.setText(_translate("Form", "Trees"))
        self.glattetGrey.setText(_translate("Form", "Glatt (grå)"))
